name: Build and push Chat-UI Manager to GitHub Container Registry

on:
  push:
    paths:
      - "chat-ui-manager-app/*"
      - ".github/workflows/build_chat_ui_manager.yml"
    branches:
      - "main"
      - "chm-1-create-chat-ui-manager-app"
    tags:
      - "v*"
  pull_request:
    paths:
      - "chat-ui-manager-app/*"
      - ".github/workflows/build_chat_ui_manager.yml"
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Permission can be added at job level or workflow level
permissions:
  contents: read # This is required for actions/checkout
  packages: write # This is required for pushing to GitHub Container Registry

jobs:
  build_and_push:
    if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/') || !endsWith(github.ref, '+on-prem')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chat-ui-manager
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: darwin/arm64,linux/arm64,linux/amd64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Begin caching work
      - name: Cache /home/bun/.bun/install/cache
        id: cache-chm-bun
        uses: actions/cache@v4
        with:
          path: home-bun-cache
          key: home-bun-cache-${{ hashFiles('bun.lock') }}
      - name: inject bun cache into docker
        # v1 was composed of two actions: "inject" and "extract".
        # v2 is unified to a single action.
        uses: reproducible-containers/buildkit-cache-dance@v3.1.1
        with:
          cache-map: |
            {
              "home-bun-cache": "/home/bun/.bun/install/cache"
            }
          skip-extraction: ${{ steps.cache-chm-bun.outputs.cache-hit }}
        # Credit to: https://docs.docker.com/build/ci/github-actions/cache/#cache-mounts &
        #            https://github.com/reproducible-containers/buildkit-cache-dance

      - name: Docker meta configuration for `chat-ui-manager` image
        id: chat-ui-manager-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=ghcr.io/hirundo-io/chat-ui-manager,enable=true
          tags: |
            type=ref,event=branch,enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=${{ github.head_ref }},enable=${{ github.event_name == 'pull_request' }}
            type=raw,value=latest,enable=${{ github.ref_name == github.event.repository.default_branch }}

      - name: Build and push `chat-ui-manager` image
        uses: docker/build-push-action@v5
        id: build-chat-ui-manager
        with:
          context: chat-ui-manager
          cache-from: type=gha
          cache-to: type=gha,mode=min,compression=zstd
          file: chat-ui-manager/Dockerfile
          pull: true
          outputs: |
            type=image,compression=zstd,push=${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'push-to-ghcr')}}
            type=docker,dest=chat-ui-manager.tar
          tags: ${{ steps.chat-ui-manager-meta.outputs.tags }}
          labels: ${{ steps.chat-ui-manager-meta.outputs.labels }}
          platforms: linux/amd64

      - uses: actions/cache@v4
        with:
          path: .trivy
          key: ${{ runner.os }}-trivy-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-trivy-

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          input: chat-ui-manager.tar
          cache-dir: .trivy
      - name: Correct Trivy cache permissions
        run: sudo mkdir -p .trivy && sudo chown -R $USER:$GROUP .trivy
